{
    'name': 'envision',
    'version': '12.0.1.0.0',
    'category': 'Extra Tools',
    'summary': 'envision Development Tutorials',
    'sequence': '10',
    'license': 'AGPL-3',
    'author': 'envision',
    'maintainer': 'Odoo Mates',
    'website': 'http://envsion.com',
    'live_test_url': 'https://www.youtube.com/watch?v=BDepk0LhVuI&list=PLqRRLx0cl0hoJhjFWkFYowveq2Zn55dhM&index=1',
    'depends': ['sale', 'mail'],
    'demo': [],
    'data': ['patient.xml'],
    'images': ['static/description/icon2.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
# Video Explanation: https://www.youtube.com/watch?v=BDepk0LhVuI&list=PLqRRLx0cl0hoJhjFWkFYowveq2Zn55dhM&index=1
